pipeline {
    agent any

    stages {
        stage('Run tests') {
            steps {
                // заходим в папку проекта и запускаем тесты
                dir('SauceDemo.Tests') {
                    bat 'dotnet test SauceDemo.Tests.csproj'
                }
            }
        }
    }

    post {
        always {
            // собираем результаты Allure
            allure(
                includeProperties: false,
                jdk: '',
                results: [[path: 'SauceDemo.Tests/allure-results']]
            )
        }
    }
}
