pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Restore') {
            steps {
                dir('SauceDemo.Tests') {
                    bat 'nuget.exe restore SauceDemo.Tests.csproj -PackagesDirectory ..\\packages'
                }
            }
        }

        stage('Build') {
            steps {
                dir('SauceDemo.Tests') {
                    bat 'dotnet build --configuration Debug'
                }
            }
        }

        stage('Test') {
            steps {
                dir('SauceDemo.Tests') {
                    bat 'dotnet test SauceDemo.Tests.csproj --logger:"trx;LogFileName=test-result.trx"'
                }
            }
        }
    }

    post {
        always {
            // Публикуем отчёт Allure
            script {
                allure([
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'SauceDemo.Tests\\bin\\Debug\\allure-results']],
                    reportBuildPolicy: 'ALWAYS'
                ])
            }

            // Сохраняем .trx как артефакты (по желанию)
            archiveArtifacts artifacts: 'SauceDemo.Tests\\**\\*.trx', allowEmptyArchive: true
        }
    }
}
